#!/bin/bash

docker exec -i slave /usr/bin/mysql -v --user root -ppassword <<EOF
CHANGE MASTER TO
  MASTER_HOST='master',
  MASTER_USER='replication_user',
  MASTER_PASSWORD='password',
  MASTER_PORT=3306,
  MASTER_LOG_FILE='$(cat .file)',
  MASTER_LOG_POS=$(cat .position),
  MASTER_CONNECT_RETRY=10;

START SLAVE;

SHOW SLAVE STATUS \G;
EOF
